# Generated by Django 6.0 on 2025-12-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='rol',
            field=models.CharField(default='Participante', max_length=50),
        ),
    ]
